import { defineType, defineField } from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  fields: [
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline',
      type: 'string',
      description: 'Main hero text in regular weight (e.g. "WE SOURCE THE WORLD.")',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroHeadlineItalic',
      title: 'Hero Headline (Italic)',
      type: 'string',
      description: 'Second line of hero text in italic (e.g. "FOR SPACES THAT FEEL INEVITABLE.")',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroSubtext',
      title: 'Hero Subtext',
      type: 'text',
      rows: 3,
      description: 'Paragraph below the hero headline',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroCtaLabel',
      title: 'Hero CTA Label',
      type: 'string',
      description: 'Text on the hero button (e.g. "EXPLORE COLLECTIONS")',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroCtaHref',
      title: 'Hero CTA Link',
      type: 'string',
      description: 'URL the hero button links to (e.g. "/collections")',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'featuredLabel',
      title: 'Featured Collection Label',
      type: 'string',
      description: 'The scrolling label in the hero (e.g. "FEATURED COLLECTION — ARTIFACTS & STATEMENT PIECES — ITALY · BALI · MEXICO")',
    }),
    defineField({
      name: 'philosophyHeading',
      title: 'Philosophy Heading',
      type: 'string',
      description: 'Main heading for the "Why Vilasa" section (e.g. "SOURCING THE WORLD.")',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'philosophyHeadingItalic',
      title: 'Philosophy Heading (Italic)',
      type: 'string',
      description: 'Italic line of the philosophy heading (e.g. "IT STARTS HERE.")',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'philosophyBody',
      title: 'Philosophy Body',
      type: 'text',
      rows: 4,
      description: 'Paragraph in the "Why Vilasa" section describing the sourcing philosophy',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'philosophyCards',
      title: 'Philosophy Cards',
      type: 'array',
      description: 'The 3 cards in the philosophy section (title, subtitle, and background image)',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'heading', title: 'Heading', type: 'string', validation: (rule) => rule.required() }),
            defineField({ name: 'sub', title: 'Subtitle', type: 'text', rows: 2 }),
            defineField({ name: 'image', title: 'Background Image', type: 'image', options: { hotspot: true } }),
          ],
          preview: {
            select: { title: 'heading', media: 'image' },
          },
        },
      ],
      validation: (rule) => rule.max(5),
    }),
    defineField({
      name: 'destinationsHeading',
      title: 'Destinations Page Heading',
      type: 'string',
      description: 'Main heading on the /destinations page (e.g. "Five countries.")',
    }),
    defineField({
      name: 'destinationsHeadingItalic',
      title: 'Destinations Page Heading (Italic)',
      type: 'string',
      description: 'Italic line of the destinations page heading (e.g. "Infinite sourcing.")',
    }),
    defineField({
      name: 'collectionsHeading',
      title: 'Collections Section Heading',
      type: 'string',
      description: 'Heading for the collections section on homepage (e.g. "Twelve worlds.")',
    }),
    defineField({
      name: 'collectionsHeadingItalic',
      title: 'Collections Section Heading (Italic)',
      type: 'string',
      description: 'Italic line of collections heading (e.g. "One vision.")',
    }),
    defineField({
      name: 'collectionsSubtext',
      title: 'Collections Section Subtext',
      type: 'text',
      rows: 2,
      description: 'Short paragraph below the collections heading',
    }),
    defineField({
      name: 'finalCtaHeading',
      title: 'Final CTA Heading',
      type: 'string',
      description: 'Closing section heading (e.g. "More than objects.")',
    }),
    defineField({
      name: 'finalCtaHeadingItalic',
      title: 'Final CTA Heading (Italic)',
      type: 'string',
      description: 'Italic lines of the closing heading (e.g. "We compose atmospheres.")',
    }),
    defineField({
      name: 'finalCtaBody',
      title: 'Final CTA Body',
      type: 'text',
      rows: 3,
      description: 'Closing paragraph inviting enquiries',
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Home Page' }),
  },
})
